name: dev deployment
on:
  # Runs on push to the develop branch
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # setup the node development environment
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install all dependencies
        run: npm install
      # run after PR merge
      - name: Run tests and generate coverage
        run: npm run coverage
      - name: Check linting errors
        run: npm run lint
  deploy:
    # deploy to heroku dev pipeline
    concurrency: 
      group: heroku_deployment
      cancel-in-progress: false
    runs-on: ubuntu-latest
    environment: development
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phantom-be-codebandits-staging"
          heroku_email: "samyshyaka@gmail.com"